### PR TITLE
fix(3141693842): amount input isn’t disabled when user isn’t logged in

### PR DESCRIPTION
**Pull request by galuzan-starkware**
### Description of the Changes

- change the `isInputDisabled` prop to be true also if the user is not logged in (!isLoggedIn = true)

Solves #[3141693842](https://starkware.monday.com/boards/2847524005/pulses/3141693842)

---

### Checklist

- [x] Changes have been done against `dev` branch, and PR does not conflict.
- [x] Manually tests of the main Application flows are done and passed.
- [ ] New unit / functional tests have been added (whenever applicable).
- [x] Automation tests are passing in local environment.
- [ ] Docs have been updated (whenever relevant).
- [x] PR title is follow the [Conventional Commits](https://www.conventionalcommits.org/) convention: `<type>[optional scope]: <description>`, e.g: `fix: prevent racing of requests`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/291)

### CODE REVIEW

**Review by yairans-starkware — CHANGES_REQUESTED** [review]
@galuzan-starkware per the design " Input field should be disabled if wallets aren’t connected. **Users should be able to click within it, but they can’t enter any text.**"
In the PRE preview the user canoon click within it

**Comment by galuzan-starkware** [comment]
@yairans-starkware @dan-ziv 
Guy's response: 
`Hi Gal, I meant that you can click on the input with the cursor and the cursor can blink there (to be honest It’s not critical, you can also disable the blink inside and don’t let anyone get there till the wallet connects) but once I type my keyboard nothing should happen, right now if I click the keyboard I can insert my input.`

I think it’s better to disable it, as I did.

So if you think the same, please approve

**Review by dan-ziv — APPROVED** [review]

**Pull request merged**
