### PR TITLE
feat: add nonce to txHash calculation

### PR DESCRIPTION
**Pull request by dan-ziv**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Checklist

- [ ] Changes have been done against master branch, and PR does not conflict
- [ ] New unit / functional tests have been added (whenever applicable)
- [ ] Test are passing in local environment
- [ ] Docs have been updated
- [ ] PR title is follow the [standard-version](https://www.conventionalcommits.org/) convention: `<type>(optional subject): <description>`, e.g: `fix: minor typos in code`

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @dan-ziv and @liorgold2)

___
*[src/constants.js, line 5 at r2](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66#-Mtm3wRd6gzxroW7VL8M:-Mtm3wRd6gzxroW7VL8N:b-fd64s2) ([raw file](https://github.com/starkware-libs/starkgate-frontend/blob/77af29c57599809ae3cbf96db94da207eceaed29/src/constants.js#L5)):*
> ```JavaScript
> 
> export const LOCAL_STORAGE_TRANSFERS_KEY = 'STARKGATE_TRANSFERS';
> export const L2_INVOKE_TX_PREFIX = '115923154332517';
> ```

do you need it to compute the hash of regular transactions?



_Code quote:_
```JavaScript
export const L2_INVOKE_TX_PREFIX = '115923154332517'
```
___
*[src/hooks/useEventListener.js, line 37 at r2](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66#-Mtm4NJvD87rnYKiPRhd:-Mtm4NJvD87rnYKiPRhe:b-wo4g30) ([raw file](https://github.com/starkware-libs/starkgate-frontend/blob/4724a093378862c21323ffa8c8612ee411feb419/src/hooks/useEventListener.js#L37)):*
> ```JavaScript
>       logger.log('Event received', {event});
>       const {to_address, from_address, selector, payload, nonce} = event.returnValues;
>       return txHash(from_address, to_address, selector, payload, chainId, nonce);
> ```

Thats a bad name if it works only for l1_handler.

Either pass a tx_hash_prefix param
or rename to L1HandlerTxHash



_Code quote:_
```JavaScript
txHash
```

**Comment by dan-ziv** [comment]
___
*[src/hooks/useEventListener.js, line 37 at r2](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66#-Mtm4NJvD87rnYKiPRhd:-Mtm55QL5KiMtx69Uuv3:bvz3mwn) ([raw file](https://github.com/starkware-libs/starkgate-frontend/blob/4724a093378862c21323ffa8c8612ee411feb419/src/hooks/useEventListener.js#L37)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Thats a bad name if it works only for l1_handler.

Either pass a tx_hash_prefix param
or rename to L1HandlerTxHash
</blockquote></details>

That's should be generic.
I will soon generlize it to pass txHashPrefix but it will be in a separate change.

**Comment by dan-ziv** [comment]
___
*[src/constants.js, line 5 at r2](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66#-Mtm3wRd6gzxroW7VL8M:-Mtm5VsU0moqUp8NqD0a:baf1ui7) ([raw file](https://github.com/starkware-libs/starkgate-frontend/blob/77af29c57599809ae3cbf96db94da207eceaed29/src/constants.js#L5)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you need it to compute the hash of regular transactions?
</blockquote></details>

I'm not sure I need it, currently, I'm calc the txHash only from messages that sent to L2.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dan-ziv, @ilyalesokhin-starkware, and @liorgold2)

___
*[src/hooks/useEventListener.js, line 37 at r2](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66#-Mtm4NJvD87rnYKiPRhd:-Mtm66RP0D74B7PpCoke:b-q6l54a) ([raw file](https://github.com/starkware-libs/starkgate-frontend/blob/4724a093378862c21323ffa8c8612ee411feb419/src/hooks/useEventListener.js#L37)):*
<details><summary><i>Previously, dan-ziv (Dan Ziv) wrote…</i></summary><blockquote>

That's should be generic.
I will soon generlize it to pass txHashPrefix but it will be in a separate change.
</blockquote></details>

I don't like it the replay to my other comment seems to indicate that you are going to support only l1_handlers but you still call this function txHash

**Comment by dan-ziv** [comment]
___
*[src/hooks/useEventListener.js, line 37 at r2](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66#-Mtm4NJvD87rnYKiPRhd:-MtmDbgsA2jldIXu7DjG:bb7f2mf) ([raw file](https://github.com/starkware-libs/starkgate-frontend/blob/4724a093378862c21323ffa8c8612ee411feb419/src/hooks/useEventListener.js#L37)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't like it the replay to my other comment seems to indicate that you are going to support only l1_handlers but you still call this function txHash
</blockquote></details>

done

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66#-:-MtmLAsH13-IRGyXaOXo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-ziv and @liorgold2)

___
*[src/hooks/useEventListener.js, line 37 at r2](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66#-Mtm4NJvD87rnYKiPRhd:-MtmKyL665OJ9HjF2XZm:bd5l6n4) ([raw file](https://github.com/starkware-libs/starkgate-frontend/blob/4724a093378862c21323ffa8c8612ee411feb419/src/hooks/useEventListener.js#L37)):*
<details><summary><i>Previously, dan-ziv (Dan Ziv) wrote…</i></summary><blockquote>

done
</blockquote></details>

thanks.

**Pull request merged**
