### PR TITLE
feat(3127762574): Inject env vars dynamically for Docker container

### PR DESCRIPTION
**Pull request by danielgluskin-starkware**
### Description of the Changes
Use dynamic images - build once for a version - regardless of the env.
Inject the env var dynamically on container start.

Solves #[3127762574](https://starkware.monday.com/boards/2847524005/pulses/3127762574)

---

### Checklist

- [X] Changes have been done against `dev` branch, and PR does not conflict.
- [ ] Manually tests of the main Application flows are done and passed.
- [ ] New unit / functional tests have been added (whenever applicable).
- [X] Automation tests are passing in local environment.
- [ ] Docs have been updated (whenever relevant).
- [X] PR title is follow the [Conventional Commits](https://www.conventionalcommits.org/) convention: `<type>[optional scope]: <description>`, e.g: `fix: prevent racing of requests`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/289)

### CODE REVIEW

**Review by dan-ziv — CHANGES_REQUESTED** [review]
@danielgluskin-starkware in general LGTM.
One comment before we can merge: create `scripts` dir and move `.sh` files under it.

**Comment by danielgluskin-starkware** [comment]
> @danielgluskin-starkware in general LGTM. One comment before we can merge: create `scripts` dir and move `.sh` files under it.

updated

**Review by dan-ziv — APPROVED** [review]

**Pull request merged**
