### PR TITLE
feat(3015821438): Change location of transfer button

### PR DESCRIPTION
**Pull request by galuzan-starkware**
### Description of the Changes

Change the TransferButton location to be below the inputs

### Checklist

- [ ] Changes have been done against master branch, and PR does not conflict
- [ ] New unit / functional tests have been added (whenever applicable)
- [ ] Test are passing in local environment
- [ ] Docs have been updated
- [ ] PR title is follow the [Conventional Commits](https://www.conventionalcommits.org/) convention: `<type>[optional scope]: <description>`, e.g: `fix: prevent racing of requests`

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/250)

### CODE REVIEW

**Comment by dan-ziv** [comment]
@galuzan-starkware please add description

**Comment by dan-ziv** [comment]
@galuzan-starkware we have some inconsistent padding at the bottom of the menu. Asked the UX designer how to solve it.

**Comment by galuzan-starkware** [comment]
> @galuzan-starkware we have some inconsistent padding at the bottom of the menu. Asked the UX designer how to solve it.

Done

**Review by dan-ziv — APPROVED** [review]

**Pull request merged**
