### PR TITLE
fix(3140547314): update discord link to the permanent master link

### PR DESCRIPTION
**Pull request by galuzan-starkware**
### Description of the Changes

- change the URL on `constants.js`

Solves #[3140547314](https://starkware.monday.com/boards/2847524005/pulses/3118317638)

---

### Checklist

- [x] Changes have been done against `dev` branch, and PR does not conflict.
- [x] Manually tests of the main Application flows are done and passed.
- [ ] New unit / functional tests have been added (whenever applicable).
- [x] Automation tests are passing in local environment.
- [ ] Docs have been updated (whenever relevant).
- [x] PR title is follow the [Conventional Commits](https://www.conventionalcommits.org/) convention: `<type>[optional scope]: <description>`, e.g: `fix: prevent racing of requests`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/290)

### CODE REVIEW

**Comment by yairans-starkware** [comment]
@galuzan-starkware pls remove `/* eslint-disable */` from https://github.com/starkware-libs/starkgate-frontend/blob/dev/src/App.js#L1.
it was there for the discord commntout but is not relevant anymore

**Comment by galuzan-starkware** [comment]
> @galuzan-starkware pls remove `/* eslint-disable */` from https://github.com/starkware-libs/starkgate-frontend/blob/dev/src/App.js#L1. it was there for the discord commntout but is not relevant anymore

@yairans-starkware  done

**Review by dan-ziv — APPROVED** [review]

**Pull request merged**
